# Discretization in Data Preprocessing

## Binarization

As the name suggests, this is the technique with the help of which we can make our data binary. We can use a binary threshold for making our data binary. The values above that threshold value will be converted to 1 and below that threshold will be converted to 0.

For example, if we choose threshold value = 0.5, then the dataset value above it will become 1 and below this will become 0. That is why we can call it binarizing the data or thresholding the data. This technique is useful when we have probabilities in our dataset and want to convert them into crisp values.

We can binarize the data with the help of `Binarizer` class of scikit-learn Python library.

In [3]:
from sklearn.preprocessing import Binarizer
import numpy as np

#creating a training data
X_train = np.array([[ 4., -3.,  2.], 
                    [ 2.,  2.,  0.], 
                    [ 0.,  -6., 7.]])
binarizer = Binarizer(threshold=0).fit(X_train)
X_train_binarized = binarizer.transform(X_train)
print("Binarized data:\n", X_train_binarized)

Binarized data:
 [[1. 0. 1.]
 [1. 1. 0.]
 [0. 0. 1.]]
