In [3]:
import numpy as np
import torch

In [13]:
softs = torch.tensor(       # shape [4,3]
  [[0.10, 0.50, 0.40],  # correct
   [0.55, 0.20, 0.25],  # wrong
   [0.60, 0.10, 0.30],  # correct
   [0.15, 0.65, 0.20]], # correct
   dtype=torch.float32)

targets = torch.tensor([1, 2, 0, 1], dtype=torch.int64)
targets = targets.reshape(4,1)  # to match softs
print(targets.shape)

probs = softs.gather(dim=1, index=targets)
# dim=1 means "collapse on cols; leaving all rows, 1 col"

print("\nComputed output probabilities: ")
print(softs)

print("\nTargets: ")
print(targets)

print("\nExtracted output probabilities: ")
print(probs)

torch.Size([4, 1])

Computed output probabilities: 
tensor([[0.1000, 0.5000, 0.4000],
        [0.5500, 0.2000, 0.2500],
        [0.6000, 0.1000, 0.3000],
        [0.1500, 0.6500, 0.2000]])

Targets: 
tensor([[1],
        [2],
        [0],
        [1]])

Extracted output probabilities: 
tensor([[0.5000],
        [0.2500],
        [0.6000],
        [0.6500]])
