In [1]:
import numpy as np
import torch

In [2]:
x = torch.tensor([1, 2, 3])
torch.sum(x)

tensor(6)

When we describe the shape of a 2D tensor, we say that it contains some rows and some columns. So for a 2x3 tensor we’ve 2 rows and 3 columns:

In [3]:
x = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])
x.shape

torch.Size([2, 3])

In [4]:
torch.sum(x, dim=0)

tensor([5, 7, 9])

In [5]:
torch.sum(x, dim=1)

tensor([ 6, 15])

In [6]:
y = torch.tensor([
     [
       [1, 2, 3],
       [4, 5, 6]
     ],
     [
       [1, 2, 3],
       [4, 5, 6]
     ],
     [
       [1, 2, 3],
       [4, 5, 6]
     ]
   ])

In [7]:
y.shape

torch.Size([3, 2, 3])

In [8]:
torch.sum(y, dim=0)

tensor([[ 3,  6,  9],
        [12, 15, 18]])

In [9]:
torch.sum(y, dim=1)

tensor([[5, 7, 9],
        [5, 7, 9],
        [5, 7, 9]])

In [10]:
torch.sum(y, dim=2)

tensor([[ 6, 15],
        [ 6, 15],
        [ 6, 15]])