# Data Preprocessing
Machine Learning algorithms are completely dependent on data because it is the most crucial aspect that makes model training possible. On the other hand, if we won’t be able to make sense out of that data, before feeding it to ML algorithms, a machine will be useless. In simple words, we always need to feed right data i.e. the data in correct scale, format and containing meaningful features, for the problem we want machine to solve. This makes data preparation the most important step in ML process. Data preparation may be defined as the procedure that __makes our dataset more appropriate for ML process__.

Data preprocessing will convert the selected data into a form we can work with or can feed to ML algorithms. We always need to preprocess our data so that it can be as per the expectation of machine learning algorithm.

## Scaling
Most probably our dataset comprises of the attributes with varying scale, but we cannot provide such data to ML algorithm hence it requires rescaling. Data rescaling makes sure that attributes are at same scale. Generally, attributes are rescaled into the range of 0 and 1. ML algorithms like gradient descent and k-Nearest Neighbors requires scaled data. 

### MinMaxScaling

We can rescale the data with the help of `MinMaxScaler` class of `scikit-learn` Python library.

In [1]:
from pandas import read_csv
import numpy as np
from sklearn import preprocessing

path = 'diabetes.csv'
df = read_csv(path)
array= df.values

Now, we can use `MinMaxScaler` class to rescale the data in the range of 0 and 1.

In [2]:
data_scaler = preprocessing.MinMaxScaler(feature_range=(0, 1))
data_rescaled = data_scaler.fit_transform(array)

In [5]:
np.set_printoptions(precision=2)
print("Scaled data:\n", data_rescaled[0:10])

Scaled data:
 [[0.35 0.74 0.59 0.35 0.   0.5  0.23 0.48 1.  ]
 [0.06 0.43 0.54 0.29 0.   0.4  0.12 0.17 0.  ]
 [0.47 0.92 0.52 0.   0.   0.35 0.25 0.18 1.  ]
 [0.06 0.45 0.54 0.23 0.11 0.42 0.04 0.   0.  ]
 [0.   0.69 0.33 0.35 0.2  0.64 0.94 0.2  1.  ]
 [0.29 0.58 0.61 0.   0.   0.38 0.05 0.15 0.  ]
 [0.18 0.39 0.41 0.32 0.1  0.46 0.07 0.08 1.  ]
 [0.59 0.58 0.   0.   0.   0.53 0.02 0.13 0.  ]
 [0.12 0.99 0.57 0.45 0.64 0.45 0.03 0.53 1.  ]
 [0.47 0.63 0.79 0.   0.   0.   0.07 0.55 1.  ]]


In [4]:
print("Orginal data: \n", array[0:10])

Orginal data: 
 [[6.000e+00 1.480e+02 7.200e+01 3.500e+01 0.000e+00 3.360e+01 6.270e-01
  5.000e+01 1.000e+00]
 [1.000e+00 8.500e+01 6.600e+01 2.900e+01 0.000e+00 2.660e+01 3.510e-01
  3.100e+01 0.000e+00]
 [8.000e+00 1.830e+02 6.400e+01 0.000e+00 0.000e+00 2.330e+01 6.720e-01
  3.200e+01 1.000e+00]
 [1.000e+00 8.900e+01 6.600e+01 2.300e+01 9.400e+01 2.810e+01 1.670e-01
  2.100e+01 0.000e+00]
 [0.000e+00 1.370e+02 4.000e+01 3.500e+01 1.680e+02 4.310e+01 2.288e+00
  3.300e+01 1.000e+00]
 [5.000e+00 1.160e+02 7.400e+01 0.000e+00 0.000e+00 2.560e+01 2.010e-01
  3.000e+01 0.000e+00]
 [3.000e+00 7.800e+01 5.000e+01 3.200e+01 8.800e+01 3.100e+01 2.480e-01
  2.600e+01 1.000e+00]
 [1.000e+01 1.150e+02 0.000e+00 0.000e+00 0.000e+00 3.530e+01 1.340e-01
  2.900e+01 0.000e+00]
 [2.000e+00 1.970e+02 7.000e+01 4.500e+01 5.430e+02 3.050e+01 1.580e-01
  5.300e+01 1.000e+00]
 [8.000e+00 1.250e+02 9.600e+01 0.000e+00 0.000e+00 0.000e+00 2.320e-01
  5.400e+01 1.000e+00]]


### Standard Scaling

Another useful data preprocessing technique which is basically used to transform the data attributes with a Gaussian distribution. It differs the mean and SD (Standard Deviation) to a __standard Gaussian distribution__ with a mean of 0 and a SD of 1. This technique is useful in ML algorithms like linear regression, logistic regression that assumes a Gaussian distribution in input dataset and produce better results with rescaled data. 

We can standardize the data (mean = 0 and SD =1) with the help of `StandardScaler` class of scikit-learn Python library.

In [9]:
from sklearn.preprocessing import StandardScaler

data_scaler = StandardScaler().fit(array)
data_rescaled = data_scaler.transform(array)
print("Standardized data:\n", data_rescaled[0:3])

Standardized data:
 [[ 0.64  0.85  0.15  0.91 -0.69  0.2   0.47  1.43  1.37]
 [-0.84 -1.12 -0.16  0.53 -0.69 -0.68 -0.37 -0.19 -0.73]
 [ 1.23  1.94 -0.26 -1.29 -0.69 -1.1   0.6  -0.11  1.37]]


## Normalization

### L1 Normalization
It may be defined as the normalization technique that modifies the dataset values in a way that in each row the __sum of the absolute values will always be up to 1__. It is also called
Least Absolute Deviations.

In [6]:
from sklearn.preprocessing import Normalizer

data_normalizer = Normalizer(norm='l1').fit(array)
data_normalized = data_normalizer.transform(array)
print("Normalized data:\n", data_normalized[0:3])

Normalized data:
 [[0.02 0.43 0.21 0.1  0.   0.1  0.   0.14 0.  ]
 [0.   0.36 0.28 0.12 0.   0.11 0.   0.13 0.  ]
 [0.03 0.59 0.21 0.   0.   0.07 0.   0.1  0.  ]]


### L2 Normalization
It may be defined as the normalization technique that modifies the dataset values in a way that in each row __the sum of the squares will always be up to 1__. It is also called least
squares.

In [7]:
data_normalizer = Normalizer(norm='l2').fit(array)
data_normalized = data_normalizer.transform(array)
print("Normalized data:\n", data_normalized[0:3])

Normalized data:
 [[0.03 0.83 0.4  0.2  0.   0.19 0.   0.28 0.01]
 [0.01 0.72 0.56 0.24 0.   0.22 0.   0.26 0.  ]
 [0.04 0.92 0.32 0.   0.   0.12 0.   0.16 0.01]]


## Binarization
As the name suggests, this is the technique with the help of which we can make our data binary. We can use a binary threshold for making our data binary. The values above that threshold value will be converted to 1 and below that threshold will be converted to 0.

For example, if we choose threshold value = 0.5, then the dataset value above it will become 1 and below this will become 0. That is why we can call it binarizing the data or thresholding the data. This technique is useful when we have probabilities in our dataset and want to convert them into crisp values.

We can binarize the data with the help of `Binarizer` class of scikit-learn Python library.

In [8]:
from sklearn.preprocessing import Binarizer

binarizer = Binarizer(threshold=0.5).fit(array)
data_binarized = binarizer.transform(array)
print("Binarized data:\n", data_binarized[0:3])

Binarized data:
 [[1. 1. 1. 1. 0. 1. 1. 1. 1.]
 [1. 1. 1. 1. 0. 1. 0. 1. 0.]
 [1. 1. 1. 0. 0. 1. 1. 1. 1.]]


## Data Labeling
We discussed the importance of good fata for ML algorithms as well as some techniques to pre-process the data before sending it to ML algorithms. One more aspect in this regard is data labeling. It is also very important to send the data to ML algorithms having proper labeling. 

### Label Encoding
Most of the sklearn functions expect that the data with number labels rather than word labels. Hence, we need to convert such labels into number labels. This process is called `label encoding`. We can perform label encoding of data with the help of `LabelEncoder()` function of scikit-learn Python library.

In [10]:
from sklearn.preprocessing import LabelEncoder

input_labels = ['red','black','red','green','black','yellow','white']
encoder = LabelEncoder()
encoder.fit(input_labels)

LabelEncoder()

In [11]:
test_labels = ['green','red','black']
encoded_values = encoder.transform(test_labels)
print("\nLabels =", test_labels)
print("\nEncoded values =", list(encoded_values))
encoded_values = [3,0,4,1]
decoded_list = encoder.inverse_transform(encoded_values)
print("\nEncoded values =", encoded_values)
print("\nDecoded labels =", list(decoded_list))


Labels = ['green', 'red', 'black']

Encoded values = [1, 2, 0]

Encoded values = [3, 0, 4, 1]

Decoded labels = ['white', 'black', 'yellow', 'green']
