# tf.placeholder and tf.Variable

- tf.Variable

    * tf.Variable is for trainable variables such as weights (W) and biases (B) for your model.

    * You have to provide an initial value when you declare it, often random.

    * Initialization of the variables is done with `sess.run(tf.global_variables_initializer())`. Also while creating a variable, you need to pass a Tensor as its initial value to the Variable() constructor and when you create a variable you always know its shape.

- tf.placeholder

    * tf.placeholder is used to feed actual training examples.

    * You don't have to provide an initial value and you can specify it at run time with the `feed_dict` argument inside `Session.run`. 

    * On the other hand, you can't update the placeholder. In comparison to a variable, placeholder might not know the shape. You can either provide parts of the dimensions or provide nothing at all.

Other notes:

* the values inside the variable can be updated during optimizations

* variables can be shared, and can be non-trainable

* the values inside the variable can be stored after training

* when the variable is created, 3 ops are added to a graph (variable op, initializer op, ops for the initial value)

* placeholder is a function, Variable is a class (hence an uppercase)

* when you use TF in a distributed environment, variables are stored in a special place (parameter server) and are shared between the workers.
    


In [1]:
import numpy as np
import tensorflow as tf

### Model parameters ###
W = tf.Variable([.3], tf.float32)
b = tf.Variable([-.3], tf.float32)

### Model input and output ###
x = tf.placeholder(tf.float32)
linear_model = W * x + b
y = tf.placeholder(tf.float32)

### loss ###
loss = tf.reduce_sum(tf.square(linear_model - y)) # sum of the squares

### optimizer ###
optimizer = tf.train.GradientDescentOptimizer(0.01)
train = optimizer.minimize(loss)

### training data ###
x_train = [1,2,3,4]
y_train = [0,-1,-2,-3]

### training loop ###
init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init) # reset values to wrong
for i in range(1000):
  sess.run(train, {x:x_train, y:y_train})

In [3]:
import tensorflow as tf

a = tf.placeholder(tf.float32)  # without shape
b = tf.placeholder(tf.float32)  # without shape
add_node = a + b    # + provides a shortcut for tf.add(a, b)

print(sess.run(add_node, {a: 3, b:4.5}))
print(sess.run(add_node, {a: [1,3], b: [2, 4]}))

7.5
[3. 7.]


In [5]:
import tensorflow as tf

x = tf.Variable(3, name="x")
y = tf.Variable(4, name="y")
f = x*x*y + y + 2

# This creates a computation graph. The variables (x and y) can be initialized and the function
# (f) evaluated in a tensorflow session as follows:

with tf.Session() as sess:
     x.initializer.run()
     y.initializer.run()
     result = f.eval()
print(result)

42


In [7]:
import tensorflow as tf

# Note: 'None' for a dimension means 'any size'.
A = tf.placeholder(tf.float32, shape=(None, 3))
B = A + 5

with tf.Session() as sess:
    B_val_1 = B.eval(feed_dict={A: [[1, 2, 3]]})
    B_val_2 = B.eval(feed_dict={A: [[4, 5, 6], [7, 8, 9]]})

print(B_val_1)
print(B_val_2)

[[6. 7. 8.]]
[[ 9. 10. 11.]
 [12. 13. 14.]]
