# nn.ModuleList and nn.ParameterList()

In [1]:
import torch
import torch.nn as nn

layer_list = [nn.Conv2d(5,5,3), nn.BatchNorm2d(5), nn.Linear(5,2)]

class MyNet(nn.Module):
  def __init__(self):
    super().__init__()
    self.layers = layer_list
  
  def forward(x):
    for layer in self.layers:
      x = layer(x)

net = MyNet()

print("Net structure:")
print(net)

print("Parameters:")
print(list(net.parameters())) 

Net structure:
MyNet()
Parameters:
[]


As you see, unlike when we would register individual modules, assigning a Python List doesn't register the parameters of Modules inside the list. To fix this, we wrap our list with the nn.ModuleList class, and then assign it as a member of the network class.

In [2]:
import torch
import torch.nn as nn

layer_list = [nn.Conv2d(5,5,3), nn.BatchNorm2d(5), nn.Linear(5,2)]

class MyNet(nn.Module):
  def __init__(self):
    super().__init__()
    self.layers = nn.ModuleList(layer_list)
  
  def forward(x):
    for layer in self.layers:
      x = layer(x)

net = MyNet()

print("Net structure:")
print(net)

print("Parameters:")
print(list(net.parameters())) 

Net structure:
MyNet(
  (layers): ModuleList(
    (0): Conv2d(5, 5, kernel_size=(3, 3), stride=(1, 1))
    (1): BatchNorm2d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): Linear(in_features=5, out_features=2, bias=True)
  )
)
Parameters:
[Parameter containing:
tensor([[[[-1.1237e-01, -1.1956e-01,  5.9429e-02],
          [-9.6323e-02, -1.1680e-01,  4.3105e-02],
          [ 3.4193e-02,  4.7696e-02, -1.6241e-02]],

         [[-1.1347e-01, -9.4593e-03, -2.2001e-02],
          [ 5.7435e-05,  2.4333e-02, -7.5014e-02],
          [-1.1859e-01,  1.2488e-02,  5.2081e-02]],

         [[ 2.8345e-02, -1.1123e-01,  1.2674e-01],
          [ 3.6649e-02, -5.0808e-02, -1.0351e-01],
          [ 1.1186e-01,  8.5879e-02,  1.0187e-01]],

         [[ 8.0822e-02, -1.4194e-01,  1.0474e-01],
          [-1.3655e-01,  6.6970e-02,  9.0123e-02],
          [-2.5106e-02,  3.3007e-03, -1.4838e-01]],

         [[-5.5691e-02, -7.8909e-02, -6.0878e-02],
          [-9.2115e-03, -7.5619e-02,  2

In [5]:
import torch
import torch.nn as nn

class MyNet2(nn.Module):
  def __init__(self):
    super().__init__()
    self.conv = nn.Linear(10,5)
    self.tens = nn.Parameter(torch.ones(3, 4))
    
  def forward(self, x):
    return self.linear(x)


myNet = MyNet2()
print(list(myNet.parameters()))

[Parameter containing:
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], requires_grad=True), Parameter containing:
tensor([[ 0.0874,  0.1637, -0.2734, -0.0602,  0.2739, -0.1190,  0.0770, -0.0888,
          0.1501, -0.1993],
        [-0.0043, -0.1117,  0.0302, -0.0467, -0.2108, -0.2999,  0.0971,  0.1101,
          0.3057, -0.1059],
        [-0.0603, -0.0845,  0.3041, -0.0814, -0.0400, -0.1872,  0.0589,  0.2009,
          0.1563, -0.0888],
        [ 0.0655, -0.2250,  0.1648, -0.1112,  0.0146,  0.1086, -0.0104, -0.2182,
         -0.2391, -0.2423],
        [-0.2911, -0.0097, -0.3097,  0.0353, -0.0232, -0.1039, -0.1356,  0.2876,
         -0.2709,  0.0236]], requires_grad=True), Parameter containing:
tensor([ 0.1846,  0.1007, -0.0670,  0.2046,  0.2345], requires_grad=True)]


In [7]:
import torch
import torch.nn as nn

class MyNet3(nn.Module):
  def __init__(self):
    super().__init__()
    self.conv = nn.Linear(10,5)
    self.net = MyNet2()
    
  def forward(self, x):
    return self.linear(x)


myNet = MyNet3()
print(list(myNet.parameters()))

[Parameter containing:
tensor([[-0.1408, -0.2268,  0.0735,  0.2179, -0.0144, -0.1694,  0.0973,  0.0340,
         -0.0937,  0.1854],
        [-0.1411,  0.3036, -0.1665,  0.1898, -0.1164, -0.1879, -0.1829, -0.2922,
          0.2521,  0.2338],
        [ 0.3066, -0.1086,  0.0779, -0.2126, -0.1165,  0.0632, -0.0601,  0.2106,
         -0.1993, -0.2691],
        [ 0.0235,  0.0087, -0.0966, -0.1650,  0.0613,  0.1027,  0.0819,  0.2495,
          0.3090,  0.0840],
        [-0.2605, -0.3033,  0.1046, -0.2619,  0.1146,  0.1011, -0.1960,  0.2169,
         -0.0398,  0.0793]], requires_grad=True), Parameter containing:
tensor([-0.0721, -0.0709,  0.2479,  0.0975, -0.2012], requires_grad=True), Parameter containing:
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], requires_grad=True), Parameter containing:
tensor([[-0.1084,  0.1117, -0.2416, -0.0555,  0.1341,  0.0020, -0.2061, -0.0143,
          0.2148, -0.2800],
        [-0.1246,  0.2321,  0.2819, -0.1580,  0.0945,  0.206

<b>Similarly, a list of tensors can be registered by wrapping the list inside a `nn.ParameterList` class.</b>