# nn.Parameter

Each `nn.Module` has a `parameters()` function which returns, well, it's trainable parameters. 

In [2]:
import torch
import torch.nn as nn

class MyNet(nn.Module):
  def __init__(self):
    super().__init__()
    self.conv = nn.Linear(10,5)
    
  def forward(self, x):
    return self.linear(x)


myNet = MyNet()
print(list(myNet.parameters()))

[Parameter containing:
tensor([[ 1.7328e-01, -2.3576e-01, -2.2630e-01,  4.4366e-02, -3.0547e-01,
         -5.6962e-02,  4.8035e-02,  3.2446e-02, -2.6323e-01,  2.9655e-01],
        [-2.1334e-01, -1.0755e-04, -2.5302e-01, -3.1503e-01, -1.1239e-01,
          2.1915e-01, -3.6488e-02,  3.0909e-01, -2.6542e-01, -1.7411e-01],
        [-2.8790e-01, -3.0210e-01, -1.6955e-01,  8.3471e-02,  1.1598e-01,
         -7.6165e-02,  6.9090e-02,  1.6730e-03, -2.6313e-01,  7.6884e-02],
        [-3.9032e-04, -1.5807e-01,  2.1170e-01,  1.7612e-01, -1.8223e-01,
         -4.8697e-02,  1.3193e-01,  2.2656e-02,  1.3206e-01, -1.8413e-01],
        [-2.8552e-01,  2.1795e-02, -2.7118e-02, -3.1052e-01, -3.0267e-01,
          2.9522e-01, -3.3172e-02, -1.5031e-01, -1.6487e-01,  2.5448e-02]],
       requires_grad=True), Parameter containing:
tensor([ 0.1376,  0.1762, -0.1358, -0.1205,  0.2511], requires_grad=True)]


If you try to assign a tensor to the `nn.Module` object, it won't show up in the `parameters()` unless you define it as nn.Parameter object. 

In [3]:
import torch
import torch.nn as nn

class MyNet1(nn.Module):
  def __init__(self):
    super().__init__()
    self.conv = nn.Linear(10,5)
    self.tens = torch.ones(3, 4)
    
  def forward(self, x):
    return self.linear(x)


myNet = MyNet1()
print(list(myNet.parameters()))

[Parameter containing:
tensor([[ 0.0524, -0.2275, -0.1358, -0.2354,  0.0169, -0.1725, -0.1389,  0.2403,
         -0.0853,  0.1450],
        [-0.1415,  0.1928,  0.2993,  0.0393, -0.1505,  0.0296,  0.2885, -0.2048,
          0.2014,  0.1587],
        [-0.0658, -0.0802,  0.0926,  0.1577, -0.0395, -0.0614, -0.1858, -0.2114,
          0.1796,  0.1703],
        [ 0.0603,  0.1483, -0.1254,  0.2032, -0.1857, -0.1582, -0.1111,  0.1859,
          0.0086,  0.2716],
        [-0.0052, -0.1230, -0.2413,  0.2933,  0.0650,  0.2763,  0.1835, -0.0740,
          0.1936, -0.1523]], requires_grad=True), Parameter containing:
tensor([-0.1712,  0.2123,  0.1667, -0.1559,  0.2988], requires_grad=True)]


In [5]:
import torch
import torch.nn as nn

class MyNet2(nn.Module):
  def __init__(self):
    super().__init__()
    self.conv = nn.Linear(10,5)
    self.tens = nn.Parameter(torch.ones(3, 4))
    
  def forward(self, x):
    return self.linear(x)


myNet = MyNet2()
print(list(myNet.parameters()))

[Parameter containing:
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], requires_grad=True), Parameter containing:
tensor([[ 0.0874,  0.1637, -0.2734, -0.0602,  0.2739, -0.1190,  0.0770, -0.0888,
          0.1501, -0.1993],
        [-0.0043, -0.1117,  0.0302, -0.0467, -0.2108, -0.2999,  0.0971,  0.1101,
          0.3057, -0.1059],
        [-0.0603, -0.0845,  0.3041, -0.0814, -0.0400, -0.1872,  0.0589,  0.2009,
          0.1563, -0.0888],
        [ 0.0655, -0.2250,  0.1648, -0.1112,  0.0146,  0.1086, -0.0104, -0.2182,
         -0.2391, -0.2423],
        [-0.2911, -0.0097, -0.3097,  0.0353, -0.0232, -0.1039, -0.1356,  0.2876,
         -0.2709,  0.0236]], requires_grad=True), Parameter containing:
tensor([ 0.1846,  0.1007, -0.0670,  0.2046,  0.2345], requires_grad=True)]


In [7]:
import torch
import torch.nn as nn

class MyNet3(nn.Module):
  def __init__(self):
    super().__init__()
    self.conv = nn.Linear(10,5)
    self.net = MyNet2()
    
  def forward(self, x):
    return self.linear(x)


myNet = MyNet3()
print(list(myNet.parameters()))

[Parameter containing:
tensor([[-0.1408, -0.2268,  0.0735,  0.2179, -0.0144, -0.1694,  0.0973,  0.0340,
         -0.0937,  0.1854],
        [-0.1411,  0.3036, -0.1665,  0.1898, -0.1164, -0.1879, -0.1829, -0.2922,
          0.2521,  0.2338],
        [ 0.3066, -0.1086,  0.0779, -0.2126, -0.1165,  0.0632, -0.0601,  0.2106,
         -0.1993, -0.2691],
        [ 0.0235,  0.0087, -0.0966, -0.1650,  0.0613,  0.1027,  0.0819,  0.2495,
          0.3090,  0.0840],
        [-0.2605, -0.3033,  0.1046, -0.2619,  0.1146,  0.1011, -0.1960,  0.2169,
         -0.0398,  0.0793]], requires_grad=True), Parameter containing:
tensor([-0.0721, -0.0709,  0.2479,  0.0975, -0.2012], requires_grad=True), Parameter containing:
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], requires_grad=True), Parameter containing:
tensor([[-0.1084,  0.1117, -0.2416, -0.0555,  0.1341,  0.0020, -0.2061, -0.0143,
          0.2148, -0.2800],
        [-0.1246,  0.2321,  0.2819, -0.1580,  0.0945,  0.206