In [1]:
import numpy as np

In [3]:
# We create a 2D array of shape 4x3
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [50, 51, 52]]) 
print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [50 51 52]]


In [4]:
# Take values without mentioning axis
indices = [2, 7]
print("Values at position 2 and 7 are: ", np.take(arr, indices))

Values at position 2 and 7 are:  [3 8]


In [5]:
# Take values with axis
indices = [0, 2]
print("Values at position 0 and 2 are: \n", np.take(arr, indices, axis=1))

Values at position 0 and 2 are: 
 [[ 1  3]
 [ 4  6]
 [ 7  9]
 [50 52]]


In [6]:
# Take values with axis
indices = [0, 2]
print("Values at position 0 and 2 are: \n", np.take(arr, indices, axis=0))

Values at position 0 and 2 are: 
 [[1 2 3]
 [7 8 9]]
