In [2]:
import numpy as np

In [3]:
np.sum([[0, 1], [0, 5]], axis=0)

array([0, 6])

In [4]:
np.sum([[0, 1], [0, 5]], axis=1)

array([1, 5])

The way to understand the “<b>axis</b>” of numpy sum is that it <b>collapses</b> the specified axis. So when it collapses the axis 0 (the row), it becomes just one row (it sums column-wise).

In [5]:
x = np.ndarray(shape=(2, 3, 4), dtype='int8')
for i in range(24):
    x.itemset(i, i+1)
print(x)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [6]:
x[0]    # axis-0

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]], dtype=int8)

In [7]:
x[1]   # axis-0

array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]], dtype=int8)

In [8]:
x[0][0] # axis-1

array([1, 2, 3, 4], dtype=int8)

In [9]:
x[0][0][0] #axis-2

1

In [10]:
np.sum(x, axis=0) # Notice that it eliminated the specified axis

array([[14, 16, 18, 20],
       [22, 24, 26, 28],
       [30, 32, 34, 36]])

In [11]:
np.sum(x, axis=1)

array([[15, 18, 21, 24],
       [51, 54, 57, 60]])

In [12]:
np.sum(x, axis=2)

array([[10, 26, 42],
       [58, 74, 90]])